# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2e503c42f09168c48b1b800a1752eedcf9994adc7bea0f85b2cea50edea590563b27e1f25de86446c885ee406ea4a9824308355104bc470de115f08d523c68

test:
  secret_key_base: 4af5d0b9606c3900460cbbffc117fc88c51ca772744cd172810c0666d278c065b58764f3b616361bc64d57732ba7e2abc917370eb4f0b9a9c29352f4b281ddc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
