# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ea48f2dc9b458871649661a975babfec360df23420822423aade48632a1f5d49eee2db102b8241ecb1b8052305da88da0a9fb65e4a702d9fa6bae90fd1b9274

test:
  secret_key_base: f3494967eac391fd9df5e84da191b0013ea7692f0adc83c08a5c3c52a2925ac30127842f5e5f388b3cb56911e3420a6e22b81918f08c3d10a12fa244c1320fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
